# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #A9B0C0

background #000000
foreground #ECE4D2
selection_foreground  #251B1A
selection_background  #7F8490
url_color             #A9B0C0

color0  #4D4140
color1  #7F8490
color2  #A9B0C0
color3  #5B5950
color4  #A9B0C0
color5  #7F8490
color6  #A9B0C0
color7  #DBD0B6
color8  #99927F
color9  #1E2439
color10 #46688E
color11 #7F8490
color12 #D97C5C
color13 #A9B0C0
color14 #C8B27D
color15 #DBD0B6

mark1_foreground #96814B
mark2_foreground #DBC592
mark3_foreground #96814B
