font_family      JetBrains Mono Nerd Font
# font_family      Undefined
# bold_font        Auto
# italic_font      auto
# bold_italic_font auto
font_size 12.0
# modify_font cell_width 80%
modify_font cell_height 4px
# modify_font baseline 3

cursor_shape block
shell_integration no-cursor
# cursor_shape_unfocused hollow
# cursor_beam_thickness 1.5
# cursor_blink_interval -1
# cursor_stop_blinking_after 15.0
cursor_trail 1
# cursor_trail_decay 0.1 0.4

mouse_hide_wait 0

url_style straight
#: can be one of: none, straight, double, curly, dotted, dashed.

sync_to_monitor yes

# enable_audio_bell yes
# visual_bell_duration 0.0

# remember_window_size  yes
# initial_window_width  640
# initial_window_height 400

window_padding_width 10 13

# window_logo_path none
# window_logo_position bottom-right

confirm_os_window_close 0

background_opacity 0.8

# kitty_mod ctrl+shift

# map kitty_mod+c copy_to_clipboard
# map kitty_mod+v paste_from_clipboard
# map kitty_mod+s  paste_from_selection

include colors.conf
