general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session && sleep 1
    # before_sleep_cmd = hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
    on_unlock_cmd = /home/vm/.local/bin/system-info
    # lock_cmd = loginctl lock-session  $XDG_SESSION_ID
    # ignore_dbus_inhibit = false
    # ignore_systemd_inhibit = false
    # inhibit_sleep = 3
}

listener {
    timeout = 2400
    on-timeout = loginctl lock-session
}

listener {
    timeout = 2440
    on-timeout = systemctl suspend
}
